# Generated by Django 4.2.7 on 2026-01-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('specification', 'Technical Specification'), ('evaluation', 'Technical Evaluation'), ('after_delivery', 'After Delivery'), ('terms_of_reference', 'Terms of Reference')], max_length=30)),
                ('project_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_replied', models.BooleanField(default=False)),
                ('scan_copy_present', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
